name: singleTrendApi

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      START_DIFF: '1'
      END_DIFF: '0'
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client
        pip install google-cloud-bigquery

    - name: Run googleTrendTopTerms.py
      run: python google/api/googleTrendTopTerms.py
